### ISSUE TITLE
Name changes? (Account names vs. UUIDs)

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#134]
As of yesterday (4th Feb 2015) Mojang allows changing the in-game user name of Mojang accounts. However the whitelists for private packs seem to rely on the user name rather than the account's UUID. Name/modpack access stealing isn't an issue - the name change system has measures against that - but people who change their display name would lose access to all private modpacks for which they are whitelisted.

**Comment by RyanTheAllmighty** [comment]
Yeah I imagine there are going to be some issues with the name changes I didn't account for, that being one of them.

Changing them to UUID's would require a rework of a few systems, although it's not vital since it just means those people need to update their name with the pack dev, it's definately something I'll work towards adding within the next week or two

**Comment by RyanTheAllmighty** [comment]
I plan to get the admin panel to start sending UUID's instead of usernames with 3.3.0.0

**Comment by flaw600** [comment]
Is it doing that currently, @RyanTheAllmighty ?

**Comment by RyanTheAllmighty** [comment]
No

**Comment by RyanTheAllmighty** [comment]
Closing as this is a big change for a small benefit
