### ISSUE TITLE
**USERDIR** should be redacted before login data in launch arguments

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#204]
Otherwise users whose Minecraft name == their computer account name do not have their `**USERDIR**` redacted correctly: http://paste.atlauncher.com/view/44a2a8b5 line 40

**Comment by RyanTheAllmighty** [comment]
I'll see what can be done about this

**Comment by flaw600** [comment]
That link dissappeared, @dgelessus. If this is still an issue, could you please repost the link? I'm curious to figure out the issue

**Comment by RyanTheAllmighty** [comment]
The issue occurs if say my Minecraft username is 'RyanTheAllmighty' and the account name for my Windows account is also 'RyanTheAllmighty' so my downloads directory is C:/Users/RyanTheAllmighty/Downloads' so when it comes time to start to censoring user data it first sensors my username so my downloads dir then comes out in the log as 'C:/Users/**USERDIR**/Downloads' so that when it comes to parse the censoring to remove the user dir of 'C:/Users/RyanTheAllmighty' it then fails as we've already censored out the username so it cannot find it.

**Comment by flaw600** [comment]
Ah. I'm sure that you're taking a look at this but I'll take a look as well sometime soon

**Comment by RyanTheAllmighty** [comment]
Yeah it's a simple fix, just reordering of censoring in the LogManager so the homedir is censored before the Minecraft username

**Comment by flaw600** [comment]
Are you going to take care of that then?

**Comment by RyanTheAllmighty** [comment]
Alright this is done pending update 3.2.3.2.

**Comment by RyanTheAllmighty** [comment]
Released
