### ISSUE TITLE
Windows 10 shows up as Windows 8.1

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#220]
As the title states, on Windows 10, the launcher console on boot shows as Windows 8.1

Not sure since it's an upgrade from Windows 8.1 if it will show the version of Windows the key is originally from, or if it's something that can be fixed launcher side.

**Comment by flaw600** [comment]
As described [here](http://stackoverflow.com/questions/32008423/javas-system-properties-returning-windows-8-1-after-upgrade-to-windows-10), it seems that this was a problem in an early build of Java 8 due to MS changing API configuration. This was fixed in jdk8u60, where it successfully detects Windows 10 as Windows 10.

**Comment by flaw600** [comment]
I suggest checking again after updating as jdk8u60 seems to have fixed the problem.

**Comment by hajile00** [comment]
I have the same issue. The fourth line at http://paste.atlauncher.com/view/870b23d8

**Comment by dgelessus** [comment]
@hajile00 You're running an outdated version of Java 7, that's why. All Java versions since 8u60 properly recognize Windows 10. Uninstall Java 7 and get the latest 64-bit Java 8 from http://java.com/en/download/manual.jsp.

@RyanTheAllmighty This should be closed as it's not an issue on the ATL side and has already been fixed for a while in Java.

**Comment by hajile00** [comment]
Thank you
