### ISSUE TITLE
Feature Request: Upate File or Notes

### ISSUE THREAD

**Issue by burlingk** [ATLauncher/ATLauncher#221]
I don't know how to add tags, so feel free to make changes to the subject line or whatever works best.

Occasionally the program will find updates and download them (usually packs.json).

It would be nice to have a description of what the changes are, even if it is a diff file or something. :-)

**Comment by RyanTheAllmighty** [comment]
At the end of the day when it comes to files in the launcher that doesn't require the launcher itself to be updated (like the packs.json) it's generally internal stuff, things end users don't need to be aware of.

At the end of the day if there are any changes which affect the user (such as new versions) they'll get notified when they go to their instances tab of a new update.

**Comment by dgelessus** [comment]
`packs.json` is the master modpack list. If that gets updated, that means that one of the many packs has had an update (this includes internal development versions) or that a new pack has been added. Most of the changes will be for packs or versions that you cannot access (because they're non-public packs) or that you aren't interested in.

If there is a launcher update, the launcher will restart, which is not the case for pack data updates. If one of the modpacks you use updates, you'll get a notification the next time you play an outdated instance of that pack. If there's a new public pack, you can see that in the Packs list.
