### ISSUE TITLE
64-bit Java installed under Program Files (x86) should not cause a warning

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#231]
https://forums.atlauncher.com/thread-12025.html

**Comment by RyanTheAllmighty** [comment]
Indeed that shouldn't happen. I'll pop a check in.

**Comment by flaw600** [comment]
Is this still a problem and if so is this a Java issue or an ATLauncher issue?

**Comment by RyanTheAllmighty** [comment]
Yes and it's an ATLauncher issue AFAIK, I've not looked into it

**Comment by flaw600** [comment]
I'll take a look at it too in the near future as well if you don't mind

**Comment by flaw600** [comment]
Ok, so I looked into it. Settings only checks if the file path contains x86 which imo is a really simplistic check. Ideally, the user shouldn't mess with the 64 bit Java default installation path, but since from what I understand, we've undertaken to fix this issue. From my research, using the Utils.is64Bit should be a good enough check since that method returns whether the JVM is 32 bit or 64 bit. If this is a good solution, I'd ask that I be able to implement it. Thoughts?

**Comment by flaw600** [comment]
Ok, so I can’t tell where we actually detect a 64 bit Windows install. Utils.is64Bit checks whether the JRE is 64 bit, not Windows. So I built a method myself, but I don’t have a system to test it on. @RyanTheAllmighty do you have a system, or know of a someone who has a test system? The fix is on my branch, 64bit-fix.

**Comment by flaw600** [comment]
So I said doing it for 3.3.0.0 would be the same…but I can’t find where we do 32 bit detection in that branch. The relevant code snippet should be the same though.

**Comment by flaw600** [comment]
So assuming that OS and OldSettings work the same way as their respective counterparts in master, this code should work as described above.

**Comment by RyanTheAllmighty** [comment]
Looks fine. Make a PR with an updated CHANGELOG.md and I'm happy to accept it

**Comment by flaw600** [comment]
Which one do you want? The one based off of the 3.3.0.0 branch? I ask because from my understanding we’re targeting two different versions so I want to do this right the first time.

**Comment by RyanTheAllmighty** [comment]
Well they're separate branches and they both have the same issue if I recall so would need to do both. Not sure if a single PR can target multiple branches or not.

**Comment by flaw600** [comment]
I don’t think they can but I’ll target both

**Comment by RyanTheAllmighty** [comment]
Released
