### ISSUE TITLE
Launcher to use supplied JRE

### ISSUE THREAD

**Issue by Ryahn** [ATLauncher/ATLauncher#255]
Not sure if you noticed recently, Java 7 has been killed and no longer downloadable. Also Mojang now supplies a JRE of Java 8 if its not installed. It also checks to make sure that they are running Java 8 Update 40.

Here is an exampled from sponge - [LINK](https://github.com/SpongePowered/SpongeCommon/blob/master/src/java6/java/org/spongepowered/launch/JavaVersionCheckUtils.java#L32)

Basically this will allow Mac, Linux and Windows users to use Java 8 as a standard. It fixes a lot of security issues also.

**Comment by RyanTheAllmighty** [comment]
Alright I'll add in a warning to users who aren't using Java 8 in 3.2.3.2.

I'm not sure about forcing it, probably won't go that far. Having the launcher download and use a JRE like the Vanilla Launcher is definitely something I want to do, may target that for 3.3.0.0 but for now I'll at least get a warning to users who aren't using Java 8 to upgrade.

Is there any specific reason Sponge chose 1.8.0_40? Is that specific version the standard or?

**Comment by gabizou** [comment]
The specific version fixed quite a few issues with streams and more specifically, the `Iterator` for `CopyOnWriteArrayList` would throw `UnsupportedOperationException`s for something as simple as [this](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/SpongeDataManager.java#L139). Aside from the various bug fixes since 1.8's release, Update 40+ is from what we've found to be the better versions handling Java 8's feature set with minimal issues.

**Comment by RyanTheAllmighty** [comment]
Alright, sounds fair enough to me. Thanks for the input @gabizou 

I may take the time to implement JRE loading like the vanilla launcher does for 3.2.3.2 as I'm waiting on some feedback from third parties before release anyway.

Thanks for the push @Ryahn this should be fairly simple to implement anyway.

**Comment by dgelessus** [comment]
"No longer downloadable" is a relative term... http://oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html

Don't get me wrong, I'm all for updating to Java 8. Just wanted to point out that Oracle doesn't actually remove old Java versions, they just move them to that dusty corner of the website so you can still get them when you need to.

Oh, and if the download links ask you to log in with an Oracle account, copy the link address and replace `otn` with `otn-pub`. Don't tell anyone at Oracle.

**Comment by s0cks** [comment]
I'm actually all for including a JDK with the ATLauncher...makes life easier knowing that people have the correct java version XD

**Comment by RyanTheAllmighty** [comment]
Alright the format I'm using for the launcher to know the Java to download and use is at https://download.nodecdn.net/containers/atl/launcher/json/java.json

I'll begin looking into implementing this tonight, should be actually very very easy.

**Comment by RyanTheAllmighty** [comment]
Question though, should we be using the JRE or JDK? Is there a difference between the java executable between the two?

**Comment by RyanTheAllmighty** [comment]
Alright so I think all user will use this downloaded Java version and it will be opt out.

I'll add in a new setting to the Java tab of the settings to 'Use System Java' which will use the systems Java instead of the one we download or the one they specify in the custom Java path

**Comment by RyanTheAllmighty** [comment]
Alright this is all implemented then.

Will be a few tweaks here and there before release but if you wanna test it out for me by downloading it at https://build.atlcdn.net/job/ATLauncher/ and then let me know how it goes and your OS and if you're using 64 bit or not.

**Comment by Ryahn** [comment]
I would like to report that its working like a charm. I have java completely removed my system and ATL still runs. (Did this for testing).

OS: Windows 10
64bit: Yes

**Comment by gabizou** [comment]
The Mac OS X app is still being built with the app signature that it needs Java 6 from Apple.

**Comment by RyanTheAllmighty** [comment]
Yes @gabizou this is fixed in the 3.3.0.0 branch, not for the 3.2.3.2 update

**Comment by flaw600** [comment]
Apple really needs to get away from needing everything marked Java 6. Or is it Adobe?

**Comment by RyanTheAllmighty** [comment]
Neither. We include in an old wrapper which is like 2 years old now which has the reliance on Java

**Comment by flaw600** [comment]
Ah. I ask because there's a general reliance on things being named Java 6 on OS X.

**Comment by RyanTheAllmighty** [comment]
Okay so a couple things to be done before release:

- [ ] check older packs to see if there are any issues launching
- [ ] check Linux installs since it's been reported a bundled JRE wont work when on a FAT partition due to not being named 'java.exe'

**Comment by RyanTheAllmighty** [comment]
This is being pushed back to 3.3.0.0 due to not having enough time to properly test and manage this

**Comment by flaw600** [comment]
My concern for packaging in a JRE - how are we going to keep it updated? Because Java updates are released more often than a version of ATLauncher is

**Comment by RyanTheAllmighty** [comment]
The JRE versions the launcher downloads is provided through a json file that we can easily update.

So there is no need for a launcher update to update the JRE used by the launcher.

**Comment by flaw600** [comment]
Oh right, duh

**Comment by RyanTheAllmighty** [comment]
This feature is being removed and moved back to 3.3.0.0 release

**Comment by RyanTheAllmighty** [comment]
I was hoping to use the same system Mojang use for their own launcher for this, but they have since switched to a native client rather than a Java based one, and those versions each hardcode the path to the json file which contains the runtime information needed within the exe for each OS.

This makes it practically impossible to use the same system Mojang use.

Two options:

- Use the old Java launchers json file and use those Java versions. This is still available at https://launchermeta.mojang.com/mc/launcher.json but is very likely not going to be updated and possibly removed at some point in the future
- Other option is to roll our own implementation. While this will mean we have absolute control over it and are not bound to Mojang making updates/removing the way they define it, it also means we need to host it and implement it on our own backend.

We may have to roll our own for full reliability, but generating those JRE downloads may be difficult, I'm investigating that now

**Comment by RyanTheAllmighty** [comment]
So I've decided that instead of automatically doing this, it will be added as a tool that uses can run to auto install and use ATLauncher's recommended Java version.

We'll host it ourselves so we're not dependant on Mojang and direct users to use it if they need to (such as for those without a GPU on intel series 1 or 2 cpu's which is known to have issues).

**Comment by RyanTheAllmighty** [comment]
Released with 3.3.0.0
