### ISSUE TITLE
Curse Redirects

### ISSUE THREAD

**Issue by reteo** [ATLauncher/ATLauncher#282]
I am attempting to install a modpack in ATLauncher, and I am getting the following log: http://paste.atlauncher.com/view/b12fb9d0

In other words, ATLauncher seems to keep trying to load the original URL (for JourneyMap), instead of following the redirects.

**Comment by reteo** [comment]
I updated the link; I had mis-entered the filename, but the issue persisted after correcting it.

**Comment by reteo** [comment]
This is apparently consistent with the site; I tried doing a direct link to both JMOD (https://minecraft.curseforge.com/projects/jmod-the-javascript-mod-loader/files/2336600/download) and JourneyMap (https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download).

**Comment by b0bst3r** [comment]
Here's how I find the links for direct downloads, I don't know if there's an easier way or not.

Go to mod curseforge page example https://minecraft.curseforge.com/projects/journeymap-32274

Click Files then the link for the download you want example https://minecraft.curseforge.com/projects/journeymap-32274/files/2354561

Click the Download button so the popup comes up which you can choose to cancel or save file (do not click either) http://i.imgur.com/kkz5QbY.png

Hover over the words https://addons-origin.cursecdn.com to get the link you need to use in the XML

Example XML

<mod name="JourneyMap" version="1.10.2-5.3.1" url="https://addons-origin.cursecdn.com/files/2350/29/journeymap-1.10.2-5.3.1.jar" file="journeymap-1.10.2-5.3.1.jar" md5="8944995c8b85da5f2d7d7a0f815cc010" download="direct" type="mods" website="http://journeymap.info" donation="https://www.paypal.com/cgi-bin/webscr?hosted_button_id=D5KK9FRAQG6DE&amp;item_name=JourneyMap+(from+curseforge.com)&amp;cmd=_s-xclick" server="no" authors="techbrew,mysticdrew" description="JourneyMap Unlimited Edition: Real-time map in-game or in a web browser as you explore. JourneyMap API: v1.9.4-1.2. Built: 2016-06-30-01:09:28."/>

**Comment by dgelessus** [comment]
I usually use the Firefox web developer tools for this. I go to the Curse page, then press F12 to bring up the web dev tools, go to the tab that shows the HTTP request list, and then click the download link. Then every step on the redirection chain is listed in the HTTP request log and I can copy the URL from there.

![grafik](https://cloud.githubusercontent.com/assets/6641959/21464866/049a15a0-c98b-11e6-8903-82aebf008a63.png)

For some reason Firefox doesn't let you copy the file URL from the download popup, or at least I haven't found out how to do that. Which is why I'm using the dev tools, then I can just copy-paste the URL instead of typing it out by hand.

**Comment by b0bst3r** [comment]
No it doesn't let you copy it but all you need at the 2 sets of numbers so I just write them down.

**Comment by RyanTheAllmighty** [comment]
Released
