### ISSUE TITLE
Java/JDK 9 compatibility

### ISSUE THREAD

**Issue by dgelessus** [ATLauncher/ATLauncher#294]
JDK 9 is [scheduled](http://openjdk.java.net/projects/jdk9/) to come out at the end of July 2017. Still a while to go, but there are early-access builds already, and it may be good to get the launcher Java 9-ready early, since there are some likely problematic changes. I've looked into this a little, and the biggest issues I've noticed so far are:

* The new module system. You now have to declare which parts of the Java libraries you want to use, beyond core language classes. This shouldn't be too complicated to fix, we just need to add a `module-info.java` and list the necessary AWT/Swing/etc. modules.
* Almost all of the undocumented `sun` and `com.sun` classes cannot be used anymore - they are intentionally not part of any public module. I know at least one place where ATLauncher uses an undocumented class (which is to get the total system RAM to display it in the log), but there may be more.
* JDK 9 now has data on what features the Java libraries supported in earlier JDK versions. This means that the launcher code has to be fully compatible with the earliest Java we want to support, at the source level. There are some odd cases which compile with JDK 8 and run on Java 6 but don't compile on JDK 9 in Java 6 mode (like JComboBox which was generified in Java 7).

I'm currently working on the Java 6 source compatibility in my fork and will probably make a PR for that soon.

**Comment by RyanTheAllmighty** [comment]
Cheers for looking into this, been out of the loop with Java for so long now I have no clue where to start. Might be an idea for me to look into this as well to kind of know at least minimally whats going on.

**Comment by dgelessus** [comment]
Ah, it seems like a `module-info.java` won't be necessary after all, because we're using Java 6 as the language level. I think they changed that at some point, which is nice. Undocumented classes are still not allowed though.

**Comment by dgelessus** [comment]
I've done some testing, and ran into a new issue. Currently the launcher downloads some libraries at runtime and adds them to the classpath, using a hack that only works when the system class loader is an `URLClassLoader`. This was the case up until Java 8, but in Java 9 the system class loader is no longer an `URLClassLoader` and the old hack doesn't work anymore.

I've tried to get around this by making a new `URLClassLoader` and using that to load the main `App` class. That doesn't work though, because the custom `URLClassLoader` uses the system class loader to load the `App` class, so `App`'s class loader is still the system class loader and not the custom one.

Sadly all workarounds that I could think of are more complicated than they should be. One option would be to make a small main class that downloads the necessary libraries, and then starts a Java subprocess for the main launcher code and sets the classpath correctly on the command line. It seems overkill though to have two Java processes for the launcher alone.

Would it be a big issue to just package the launcher's libraries in the jar? This would remove the need for any classpath hacks.

**Comment by RyanTheAllmighty** [comment]
I suppose we can add them into the jar if absolutely necessary. They weren't put in there to begin with simply so we didn't fatten up the download. Adding them in would quadruple it's size and add in 3.5MB to each and every download/update.

I'm okay and have come to terms with this now (given NEXT will be along the lines of 80MB) so I'm okay with this.

I assume launching packs with all those classpath stuff isn't an issue since it's making a new process?

**Comment by dgelessus** [comment]
Launching packs is fine, because we're starting a new Java process and can control almost anything using command-line arguments if necessary. The trouble here is with modifying the classpath at runtime, which was never officially supported and is now basically impossible.

But to be honest I'm not sure if Minecraft will even run on Java 9, considering how much trouble I'm having with ATLauncher already. :P

**Comment by RyanTheAllmighty** [comment]
Yeah, well the work you've done so far is great, so if we need to support Java 9 we can :) But yeah seeing all these changes, I think it will be nearly next to impossible to support Java 9 without Forge, Minecraft and mods all changing things to support it right?

**Comment by dgelessus** [comment]
Yeah, depending on how bad Java 9 breaks things, we might have to wait a while until mods work with Java 9. In the worst case we would have to wait for the entire dependency chain (Minecraft dependencies > Minecraft > Forge > the mods) to be Java 9-ready, so perhaps I am jumping the gun a little with Java 9 support this early. But since the Java version used by the launcher is independent of the one used by Minecraft, the launcher can run on Java 9 while using Java 8 for Minecraft.

**Comment by jamierocks** [comment]
Don't bother with SE 9, I doubt LaunchWrapper is going to get support (see https://github.com/Mojang/LegacyLauncher/pull/11#issuecomment-247742636).

**Comment by dgelessus** [comment]
OK, that response is kind of to be expected. I guess it all depends on what Mojang decides in the end, and whether they will support Java 9 or stay on their custom Java 8 build forever.

Anyway, I'll still play around and see if the launcher can be reasonably made to run on Java 9. If it doesn't require massive restructuring, it might still be good to support Java 9, if only to display a friendly message telling people that Minecraft/Forge/whatever doesn't work on Java 9 (yet?) and that they need to downgrade.

**Comment by flaw600** [comment]
Well it's a good thing then that Java doesn't uninstall older versions of Java when updating (as unsafe as that is). I'm curious to see Oracle's reasoning for supposedly breaking changes (of which affect many from what I hear)

**Comment by jamierocks** [comment]
The changes are breaking for Minecraft, for what many would perhaps call an abuse of available resources :p

**Comment by dgelessus** [comment]
@flaw600 The main breaking change is that use of `com.sun.*` and `sun.*` classes is now disallowed completely, as opposed to being just bad practice. This is based on the (also new) module system, which required some changes to class loading, which resulted in the default class loader no longer being a `URLClassLoader`. This is an issue because a very popular hack to extend the classpath at runtime assumes that the default class loader is a `URLClassLoader`. ATLauncher's code used undocumented classes as well as the class loader hack.

To be fair, these changes should in theory not cause any compatibility issues, because they only affect undocumented classes and assumptions that were never guaranteed to be true in future Java versions. But as you can probably imagine, it can be very tempting to use undocumented behavior in some cases. (There are also people who simply don't care whether something is documented or not.) This means that lots of code out there relies on undocumented behavior and is incompatible with Java 9 because of that.

**Comment by flaw600** [comment]
@dgelessus agreed, but as you pointed out, a lot of developers used undocumented classes as well as/including `com.sun.*` and `sun.*` as well as - as you pointed out - said popular hack. Oracle's developers should've known the current state of development using Java rather than what is theoretically bad practice lol. What I was really referring to lol is the need for the module system which imo is rather unnecessary.

**Comment by dgelessus** [comment]
The module system also has some uses other than keeping people from using private APIs. I think one of the motivations was to allow splitting a single library into different modules, so you can safely install or distribute a subset of the library. (Yes, you can specify which modules a module depends on of course.) This was applied to the Java standard libraries, so now you have modules like `java.base` for core language classes, `java.desktop` for GUI stuff, `java.logging` for the logging framework, etc. There are also modules like `java.compact1` or `java.se` to use a specific set of APIs.

This is basically irrelevant to ATLauncher of course, there's no real use for the module system in the launcher. It's not even possible to fully use the module system if the language level is lower than Java 9. But we still have to deal with undocumented classes being forbidden. `:P`

**Comment by flaw600** [comment]
fSee, like I still don't understand the point of that. First, build systems would have to be updated to support the module system if I understand the system correctly, which would happen slowly, if at all (most development - especially at the enterprise level - is still on Java 7, much less 8 or 9, so build systems have little incentive to provide support for some time). Secondly, most developers I think either use an IDE or some other system that allows for auto-imports (or some sort of import/dependency management especially when using a dependency management/build system), thereby rendering the module system pointless as I understand it. This may come across as being resistant to change, but I genuinely do not understand how the module system is actually effective and useful in ways not otherwise established. 

Note that at this point (or even from the beginning really), I wasn't debating about having to deal with the breaking changes, merely that I'm trying to figure out how the breaking changes are actually helpful to developers, be it in the short term or the long-term

**Comment by dgelessus** [comment]
If you're interested in the detais, [this](http://openjdk.java.net/projects/jigsaw/spec/sotms/) is a relatively detailed explanation of what the module system does and how you would use it.

Yes, build systems would need updating of course. (Gradle doesn't even think that `1.9` or `9` is a valid Java version.) That will happen over time. I can't really comment on how this affects enterprise projects, but just because they don't use new features a few days after they come out (for good reason) doesn't mean that new features are pointless. Modules change nothing about imports, by the way - you can't `import java.base` and get all classes from all packages, you need to import classes and packages just like before.

**Comment by VorlMaldor** [comment]
Have there been any updates on this?

**Comment by jamierocks** [comment]
Still not really a thing for modded, not too pressing imo.

**Comment by RyanTheAllmighty** [comment]
Only thing I can see stopping this is the way the launcher gets the users system memory in order to show a dropdown list of ram to pass to Minecraft, as well as determining the default value for this setting.

From a quick google, there is no way now to get system ram within Java, you'd have to resort to parsing /proc/meminfo on *nix and run some command line to parse for Windows (which given the varying types of Windows installs makes this potentially tricky).

So this may not eventuate, as there is no simple way to guarantee a correct reading.

Alternative is to just let the user free form choose their ram, and default it to 4gb.

Problem will be that for some users this will mean that the launcher will just outright not launch due to not having enough ram, and will cause more support cases to come through since it is freeform.

Not sure on how to proceed

**Comment by RyanTheAllmighty** [comment]
Okay classloader hacks are now gone and the above issue I mentioned is now taken care of thanks to a static go binary using https://github.com/pbnjay/memory

So now launcher is compatible with Java 9. Will go out with release 3.2.7.0

I'll need to do some error checking to make sure if the binary fails, users can still set their ram manually

**Comment by RyanTheAllmighty** [comment]
Fixed with 3.2.7.0
