### ISSUE TITLE
Process Priority Option

### ISSUE THREAD

**Issue by tenten8401** [ATLauncher/ATLauncher#307]
Can we have the option to set the Minecraft process priority? Possibly make it a windows only thing, as Linux doesn't seem to have the following problem (haven't tested for myself). I have a very heavy pack and the mouse spazzes out quite a lot with the priority at normal. When setting it to below normal, the issue vanishes. At first I blamed it on Optifine, but removed it and saw it still popped up occasionally, just not as often. An option to change the priority automatically would be nice, even if other packs don't have this issue, possibly to make the computer more responsive if it's a heavy pack.

**Comment by dgelessus** [comment]
First of all, this is entirely OS-specific. Java provides no APIs to modify the priority of itself or another process, probably because different OSes have different concepts of process priority and how it can be changed. Windows has the [process priority class](https://msdn.microsoft.com/en-us/library/windows/desktop/ms685100(v=vs.85).aspx) system that you're describing. On Unixes there is [nice](http://www.unix.com/man-page/posix/3p/nice/), which can be used to reduce the running process's scheduling priority (raising requires super-user rights, managing other processes is not standardized in POSIX it seems).

It would probably be possible to call the OS-native command-line tools to change the priority of the Minecraft Java process at launch. [This SO question](https://stackoverflow.com/questions/6223765/start-a-java-process-at-low-priority-using-runtime-exec-processbuilder-start) has some answers that explain how that can be done on Windows. I'm not a big fan of that though, as it requires calling `cmd` by hand, which requires manual escaping/quoting to work properly, and that is always a potential security issue.

However I don't really think it would be a good idea to add this feature to the launcher. The effect of the process priority setting is very dependent on the PC setup - number of cores, processor speed, other running programs, etc. Reducing the process priority might help on one system, but it could be bad on a different system, or have no visible effect at all. It's certainly not something that packs should be able to configure for all users in the XML. To me it sounds like the mouse issue itself could just be the result of a specific hardware and software combination - actually, didn't you say a few days ago in the Discord that unplugging your webcam fixed the bug, or something like that?

Also, according to the MSDN docs, if a process with priority Normal or lower launches another process, that process inherits the lower priority. Have you tried making a batch file that runs ATLauncher with below normal priority, using the [`start`](https://technet.microsoft.com/en-us/library/cc770297%28v=ws.11%29.aspx) command? Something like this:

```batch
start /belownormal /b ATLauncher.exe
```

**Comment by tenten8401** [comment]
I've had 4 people try my pack though and all say it spazzes out for them. It would be a bit difficult to implement but I'm willing to bet I'm not the only one with this problem. (maybe)

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

If this is necessary later on, it can be recreated, but seems like it's not something simple/easy to add in and test.
