### ISSUE TITLE
forge-1.12.2-14.23.2.2629-universal or higher is not supported

### ISSUE THREAD

**Issue by superninjakiwi** [ATLauncher/ATLauncher#332]
### Description

forge-1.12.2-14.23.2.2629-universal or higher is not supported. Attempting to install this version of forge, or any above it, crashes the game before start.

### Steps to Reproduce

1. Install forge-1.12.2-14.23.2.2629-universal or higher in any instance.
2. Immediately crash

**Expected behavior:** Forge allowing minecraft to open

**Actual behavior:** Forge crashes any instance regardless of other mods or lack thereof

### Additional Information

Versions below forge-1.12.2-14.23.2.2629-universal do not crash the game.

**Comment by RyanTheAllmighty** [comment]
Please provide some logs of the crash.

I think it's most likely due to not having the correct libraries. Unfortunately forge isn't something you can just drop in, it needs a bunch of it's own libraries, which generally don't change between Minecraft versions, but in 1.12.2 they have.

Give me some logs of the crash and I can confirm that or see what the issue is.

**Comment by superninjakiwi** [comment]
https://paste.atlauncher.com/view/d1f5fb8f

**Comment by jamierocks** [comment]
Looks like your missing libraries.

**Comment by RyanTheAllmighty** [comment]
Did you just put forge in manually? Forge needs a bunch of libraries installed in order to work.

You will be best installing MultiMc if you want to create a pack and install forge into vanilla Minecraft as they support it properly, unlike ATLauncher.
