### ISSUE TITLE
The launcher deletes mods from the mod folder instead of updating them in a custom instance.

### ISSUE THREAD

**Issue by Zippomoon** [ATLauncher/ATLauncher#381]
**Describe the bug**
In my custom 1.14.4 instance when I try to update a mod it just deletes whats there instead of replacing it with the new version, but it still shows up in the Edit Mods window.

- OS: Windows 10
- Version: 3.3.4.2

**Comment by Zippomoon** [comment]
Also, installing new mods from curse works fine just updating them is broken.

**Comment by RyanTheAllmighty** [comment]
@Zippomoon can you confirm if you're selecting a new version from the dropdown list when you go to update a mod? The launcher defaults to your current version of the mod installed, rather than the latest version.

When I choose a newer version, it works fine, but when I use the default item (which is the same version) the file deletes itself.

I'll fix it so that when you select the same version, it doesn't delete itself, and so the default selected item in the update dialog is the newest version of the mod

**Comment by Zippomoon** [comment]
Can confirm that I am NOT selecting a new version on the mods that are getting deleted, note that the version selection menu for these same mods appear even thou the newest 1.14.4 version of those mods are installed BUT these mods do have 1,15 versions which may be causing the issue.

**Comment by RyanTheAllmighty** [comment]
Thanks for confirming. Yeah I've fixed that issue up also showing updates when there's newer version in another version.

I'll release an update today to fix these issues

**Comment by Panderine** [comment]
Hi, I can confirm the same issue. The last comment mention a release around a month ago but the last available release is far older. Am I missing something?

**Comment by RyanTheAllmighty** [comment]
Released with 3.3.4.3

Sorry for the delay on releasing this
