### ISSUE TITLE
Vanilla with Forge Server unable to be installed (Ubuntu 20.04)

### ISSUE THREAD

**Issue by LvdT** [ATLauncher/ATLauncher#386]
**Describe the bug**
When creating a new Vanilla + Forge Server the following error is given:

> Failed to process argument with value of **USERSDIR**/servers/MapsForge/libraries/de/oceanlabs/mcp/mcp_config/1.15.2-20200515.085601/mcp_config-1.15.2-20200515.085601-mappings.txt as the local file **USERSDIR**/temp/VanillaMinecraftwithForge_1152/loader**USERSDIR**/servers/MapsForge/libraries/de/oceanlabs/mcp/mcp_config/1.15.2-20200515.085601/mcp_config-1.15.2-20200515.085601-mappings.txt doesn't exist

**To Reproduce**

1. Go to Vanilla Packs
2. Click on Create Server
3. Click on Install
4. The installation will fail halfway with the error given above.

**Desktop (please complete the following information, or remove if not applicable):**

- OS: Ubuntu 20.04
- ATLauncher Version 3.3.5.0

**Comment by RyanTheAllmighty** [comment]
Can you confirm the following:

- What version of Forge and Minecraft were you trying to create the server for
- Have you tried with older Minecraft and/or Forge versions to see if it's all of them, or just specific versions
- Can you provide a full log using the Upload Logs button on the ATLauncher console ![](https://cdn.atlcdn.net/UploadLogs.gif)

**Comment by LvdT** [comment]
I tried to install MC 1.15.2 with Forge 31.2.5 (default options).
I also tried 1.15.2/31.2.0, 1.15/29.0.4 and 1.14.4/28.2.16, they don’t work. 
Logs are here: https://paste.atlauncher.com/view/56fd8175

**Comment by RyanTheAllmighty** [comment]
I can replicate this in a Ubuntu 20.04 VM, but all is fine on my Windows machine.

Will investigate as to why

**Comment by RyanTheAllmighty** [comment]
Okay I've finally figured out why this is happening.

When Forge is generating the mappings for Minecraft, it's generating the path to those mappings, which differ between Windows and *nix systems:

- C:\ATLauncher\servers\VanillaMinecraftwithForge\libraries\de\oceanlabs\mcp\mcp_config\1.15.2-20200515.085601\mcp_config-1.15.2-20200515.085601-mappings.txt
- /ATLauncher/servers/VanillaMinecraftwithForge/libraries/de/oceanlabs/mcp/mcp_config/1.15.2-20200515.085601/mcp_config-1.15.2-20200515.085601-mappings.txt

The launcher code is looking for that path starting with `/`, and if it does it will check if the file exists, and if it doesn't, stop the install.

https://github.com/ATLauncher/ATLauncher/blob/32ee0ed3f0b0181a68f2a83c2db4191ffe7a82ab/src/main/java/com/atlauncher/data/minecraft/loaders/forge/Processor.java#L133-L146

Since Windows paths don't start with `/` it was not checking if the file exists.

Since the path in question is an output path, it's not expected to exist in the first place, so the check if the file exists shouldn't be happening at all.

I'll fix this up and then release in the next release today.

**Comment by LvdT** [comment]
Great, thanks!

**Comment by RyanTheAllmighty** [comment]
Released with version 3.3.5.2 of the launcher
