### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [ATLauncher/ATLauncher#401]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing ATLauncher on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by jamierocks** [comment]
That looks a dreadfully in-efficient way to manage an ATLauncher installation - why would you want a containerised installation of Java?

ATLauncher is already a "portal" installation, so this just seems a waste of time and storage - alongside actually being somewhat frustrating as I would understand - specifically choosing a specific Java version to both run the launcher and the game (correct me if we can use system packages for one or both).

Forgive me if I'm ill-informed, but this would seem to be of little value to people using ATLauncher.

**Comment by RyanTheAllmighty** [comment]
This would be up to the community to create and maintain the same way the AUR packages are done so.

**Comment by nickavem** [comment]
I've created a [flatpak build](https://github.com/nickavem/io.atlauncher.ATLauncher) that I would say is production ready. It is marked as community maintained and uses the io.atlauncher.ATLauncher name to differentiate it even further.

I know the team behind ATLauncher has had reservations about flatpak in the past, but it has become an important platform in Linux. 

1. Flathub generally has a better community than the AUR, and I *rarely* see packages go outdated. I will be monitoring the ATLauncher upstream for new releases and will really only have to change a couple of numbers and a checksum for updates (if somebody else hasn't already submitted a PR).
2. This will make your app more discoverable on [Flathub](https://flathub.org/home), Gnome Software, KDE Discover, and other Linux app stores. I can even include donation links and website homepages if you wish:
![Screenshot from 2021-05-17 08-34-40](https://user-images.githubusercontent.com/72708798/118489415-cd6ce380-b6ea-11eb-96ce-2766dd06ab99.png)
![Screenshot from 2021-05-17 08-35-47](https://user-images.githubusercontent.com/72708798/118489512-e8d7ee80-b6ea-11eb-9188-a1351019c706.png)
3. Java will automatically be on the latest OpenJDK 8 version, meaning there is one less thing to worry about. If there is demand, I could probably also add a way to use more than one version like the flatpak Minecraft build. Things like desktop icons will also be managed automatically.

I feel it would be better not to publish without you all's wishes, but I do hope you consider.

**Comment by RyanTheAllmighty** [comment]
I'm happy to reconsider Flatpak simply because it's more accessible for some people.

But to point 1, we've moved to managing that sort of thing within this repo. For instance the AUR packages are officially maintained within this repo (https://github.com/ATLauncher/ATLauncher/tree/master/packaging/aur) and published automatically on release with GitHub actions (https://github.com/ATLauncher/ATLauncher/tree/master/.github/actions/publish-to-aur) so they are never out of date.

I'd definitely not consider releasing anything without that.

Seems you're familiar with the Flatpak/Flathub process, is this something we can achieve here? Like with AUR it's a simple process of just pull a git repo from AUR, make your changes, push up the changes and you're good, the package is updated. From memory, Flathub had some weird nonsense with using their GitHub repo, but I only breifly looked.

**Comment by nickavem** [comment]
Flathub is similar. We'll just need to get the build approved, then we'll get a repo like [https://github.com/flathub/com.mojang.Minecraft](https://github.com/flathub/com.mojang.Minecraft) where we can push all changes that will be automatically built and deployed with the Flathub CI.

**Comment by nickavem** [comment]
I'm not sure is this has been doen before, ans once again flatpak updating is usually as easy as changing some numbers and a checksum, but if you are *really* worried about it, I don't see why it wouldn't be possible.

**Comment by RyanTheAllmighty** [comment]
Definitely need to be able to automate the process. I know what happens when packages don't get updates cause people don't have time, or go away from the scene all together. It happened with the AUR package which is why it was completely automated.

From a quick look at that example and https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app it looks like we get full write access, so it should be possible. 

But yeah I 100% will require it to be automated (preferably by us and this repo) in some way before I'd move forward.

If you want to essentially take what you've done in your repository, copy it into `packaging/linux/flatpak` and then make a PR then I can take a look about getting it submitted and getting the update process worked out.

Couple things:

- rename it from `io.atlauncher.ATLauncher` to `com.atlauncher.ATLauncher` to match our existing namespace
- can we take the description from the existing linux desktop file (https://github.com/ATLauncher/ATLauncher/blob/master/packaging/linux/_common/atlauncher.desktop)
- change the appdata.yml you have to match the existing metainfo we have as much as possible (https://github.com/ATLauncher/ATLauncher/blob/master/packaging/linux/_common/atlauncher.metainfo.xml)

Don't worry about trying to use like the `_common` folder or anything, just duplicate things you need in the flatpak folder and once it's on the store and automated, then I'll build that into the updater

**Comment by nickavem** [comment]
I opened a PR. I have to do some work now, but will give automation a shot as soon as I can.

**Comment by Anas-Sherif** [comment]
any updates?

**Comment by RyanTheAllmighty** [comment]
Not yet no
