### ISSUE TITLE
Can't add mods via the Instances/Edit Mods/Add Mod button on MacOS Big Sur

### ISSUE THREAD

**Issue by elite001mm** [ATLauncher/ATLauncher#430]
**Describe the bug**
When attempting to add a .jar to my mod folder via the "Add Mod" button under the "Edit Mods" section of an instance, the launcher doesn't seem to be able to read any of my Downloads/Documents/Desktop, etc directories. It sees those directories, but it displays them as empty, and therefore I can't add external mods to an instance using the standard method. I also tried manually giving ATLauncher full disk access in system preferences to no avail.

I posted on the ATLauncher Discord and a workaround was suggested: to drag and drop the mod files directly onto the Add Mods dialog from Finder (the one that shows enabled and disabled mods side by side)

This workaround does indeed bypass the problem and it lets me add mods to my instance. It seems to be some kind of permission issue or something. MacOS apps usually request to access these directories (Desktop, Downloads, etc.) that are missing, and ATLauncher never asked to access them, so I think that might be part of the problem. It can't see them because it never asked to?

**To Reproduce**

1. Be on MacOS Big Sur
2. Create an instance
3. Under the instance, click "Edit Mods"
4. In the popup window, click "Add Mod"
5. In the new popup window, click "Select"
6. Navigate to a directory like Documents, Downloads, etc and see that there is nothing there

**Screenshots**
![Screen Shot 2021-01-02 at 11 31 32 PM](https://user-images.githubusercontent.com/12221849/103509366-95928d00-4e28-11eb-9820-976217bb0ece.png)

**Desktop (please complete the following information, or remove if not applicable):**

- OS: [MacOS Big Sur 11.0.1]
- Version [3.4.1.0]

**Comment by RyanTheAllmighty** [comment]
Due to the way the app itself works, it isn't a native app, it essentially runs a script which will then invoke the Java on your system and then launch the jar file inside the app.

Because of this, adding the ATLauncher app itself to have Full System Access doesn't work. I even tried adding in java itself to have full disk access, but no luck.

I've found a solution which is to use the native OS file picker instead of the inbuilt Java one. I'll make this an option in a new update which will default to using the native file picker on OSX which bypasses the need to grant full disk access (not that you could anyway).

Thanks for alerting me to this issue

**Comment by RyanTheAllmighty** [comment]
Released with version 3.4.2.0
