### ISSUE TITLE
Have to launch server twice due to EULA

### ISSUE THREAD

**Issue by Maxo6453** [ATLauncher/ATLauncher#523]
I noticed that when trying to set up a Minecraft server on ATLauncher you have to agree to the EULA by changing the command in eula.txt to true. This is fine, but the issue is that you have to launch the server to generate the eula.txt file, agree to the EULA, and launch the server again. I propose that the eula.txt file should generate alongside launchServer.sh and all the rest of it. I believe this would be a simple fix to an annoying problem. Thanks in advance!

**Comment by RyanTheAllmighty** [comment]
Since the EULA is a legal requirement, which can change over time with different versions, this is not something that we'll ever look to automate the acceptance of.

Looks like there is an argument that can be passed when launching (`-initSettings`) which will generate the server.properties and eula.txt files from version 18w48a onwards. I'll add that command to generate those on that version and newer, but for anything else, or automatically accepting the EULA, no, won't be done.
