### ISSUE TITLE
Tray Icon Right Click menu entries only work after multiple attempts on Linux (Gnome)

### ISSUE THREAD

**Issue by tealLoop** [ATLauncher/ATLauncher#553]
After right clicking the tray icon, hovering on an entry doesn't seem to select it, and trying to select an option, for example, the option to quit the launcher (last option), it either completely ignores it, or just selects the top option (kill the minecraft process), it only works as intended after multiple attempts

Quickly double right-clicking the icon seems to improve chances but its still not working first try

I also tried both the .jar file and the rpm, both have the same issue

**To Reproduce**
(Most likely needs to be on Gnome)
Open ATLauncher
Make sure the "Show Tray icon" option is enabled in settings
Right clicking the tray icon and try selection one of the menu entries, like the one to quit the launcher

**Expected behavior**
Right clicking on the tray icon and hovering on an option will highlight it, and clicking on it would do the intended action first try, without needing to do multiple attempts for it to work

**Video Showing Problem**
https://drive.google.com/file/d/1-mUDvjtPUs6sJjsMIUANLLvUGKq4V23S/view?usp=sharing

**System information**

- OS: Fedora 35, Gnome 41.3
- Java Version: OpenJDK 11 x86_64

**Comment by RyanTheAllmighty** [comment]
Is there something specific you're doing in Fedora/Gnome to show the tray icon as shown in your video? I setup a default Fedora 35 install and don't see any icons in the top right with the launcher open other than  the default network/power option.

**Comment by tealLoop** [comment]
oh yeah, i forgot that's not default behavior

I was using the "AppIndicator and KStatusNotifierItem Support" gnome extension by the Ubuntu team
https://github.com/ubuntu/gnome-shell-extension-appindicator
https://extensions.gnome.org/extension/615/appindicator-support/

its not default in Fedora but it is on Ubuntu if i remember correctly

**Comment by RyanTheAllmighty** [comment]
Ahh cheers, yeah I did install appindicator extension but had some issues with it not showing, but thanks for the links, should be able to figure it out now and see if I can replicate.

**Comment by RyanTheAllmighty** [comment]
Alright so I managed to get the Gnome extension installed and seems to work fine for me. I did a couple changes to the tray icon recently since last release, so maybe that helped the issue?

I notice the icon looks like absolute garbage, so I'll see if I can fix that up, but when the next update goes out, this issue will auto close, if you notice it still happening after that, please feel free to comment, but might be a bit hard to track down as it seemed to be okay for me, and as with the nature of Linux, things seem to be generally just happening on a single persons machine for their exact configuration of components somehow, but yeah let's see how the next update goes for you and go from there.

**Comment by RyanTheAllmighty** [comment]
A quick google looks like this might be an issue with Gnome/Fedora itself (https://bugzilla.redhat.com/show_bug.cgi?id=1014448) that just got ignored. So there might realistically not be much I can do about it unfortunately
