### ISSUE TITLE
"Couldn't move file" error (mac)

### ISSUE THREAD

**Issue by uthbees** [ATLauncher/ATLauncher#584]
On mac, when I try to download a modpack that requires a mod which has third party downloading disabled, the browser page for the first mod like that is opened and I can download the mod (or it'll download itself in five seconds), but then ATLauncher stops and gives an error saying, "\<modpack\> wasn't installed. Check error logs for more information." [Here is the log for your convenience.](https://github.com/ATLauncher/ATLauncher/files/8746866/log.txt)

Workaround: once I got that error message, I had the mod in question in my downloads folder and also in the ATLauncher mods folder. For some reason, dragging the file from my downloads folder into the ATLauncher folder and choosing to replace the file there did the trick, although I had to repeat this process for each mod with the curseforge option enabled - trying to create the instance, failing, and dragging the new mod between folders.

Note - this issue doesn't appear on windows 10. Everything worked flawlessly for me there - I didn't even have to do anything, it just opened all the tabs and downloaded everything for me!

**Comment by RyanTheAllmighty** [comment]
Yeah later versions of OSX have some sandboxing to apps, so the launcher doesn't get access to files outside of it's own and you see this sort of behaviour.

You either need to download the files direct to the launchers downloads folder, or alternatively ditch the app and just use the Jar version of the launcher from https://atlauncher.com/downloads which doesn't have these restrictions

This is likely something that might get fixed by #559 when we can add in custom entitlements, but yeah this isn't something we can fix now, but there's a couple alternatives above
