### ISSUE TITLE
Launcher gets confused about updating mods that don't increment their version number

### ISSUE THREAD

**Issue by Flypaste** [ATLauncher/ATLauncher#626]
Launcher gets confused about updating mods that don't increment their version number.

1. Install the 1.18 version of [Launchpads](https://www.curseforge.com/minecraft/mc-mods/fabric-launchpads)
2. Have ATLauncher check for an update to the mod for your 1.19 instance
3. Tell it to install the updated mod
4. It just loads the cached 1.18 version of the mod because they're both called version 1.2.0

I'm not actually certain if this repro will work for someone who doesn't have the 1.18 version cached - the launcher might erroneously download the 1.19 version instead. So just do the reverse. Cache the 1.19 version and then try to install the 1.18 on an instance, and it should erroneously load the 1.19 version.

**Comment by RyanTheAllmighty** [comment]
The launcher doesn't use the version numbers to determine mod updates or anything at all for that matter. It downloads the file you choose and select when updating the mod.

The issue in this case is that this mod is opted out of third party downloads, and since it uses the same exact filename between MC versions, the launcher currently assumes the file is good without verifying hashes, with a nice fat TODO in the code left from the mayhem that was the day CurseForge started enforcing that api change:

https://github.com/ATLauncher/ATLauncher/blob/70f63bf0fc4fa0639184b5add650e9ae3665dce3/src/main/java/com/atlauncher/data/Instance.java#L1268-L1269

I'll fix it up to verify the hashes
