### ISSUE TITLE
Support Quick Play

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#748]
23w14a added in Quick Play which allows launching directly into a server, realm or singleplayer world (https://www.minecraft.net/en-us/article/minecraft-snapshot-23w14a).

Would be good to have a setting per instance to auto launch into a server (old MC versions support `--server` and `--port`) or singleplayer world

**Comment by RyanTheAllmighty** [comment]
Looks like it's in the game arguments in the json definition now:

```
      {
        "rules": [
          {
            "action": "allow",
            "features": {
              "has_quick_plays_support": true
            }
          }
        ],
        "value": [
          "--quickPlayPath",
          "${quickPlayPath}"
        ]
      },
      {
        "rules": [
          {
            "action": "allow",
            "features": {
              "is_quick_play_singleplayer": true
            }
          }
        ],
        "value": [
          "--quickPlaySingleplayer",
          "${quickPlaySingleplayer}"
        ]
      },
      {
        "rules": [
          {
            "action": "allow",
            "features": {
              "is_quick_play_multiplayer": true
            }
          }
        ],
        "value": [
          "--quickPlayMultiplayer",
          "${quickPlayMultiplayer}"
        ]
      },
      {
        "rules": [
          {
            "action": "allow",
            "features": {
              "is_quick_play_realms": true
            }
          }
        ],
        "value": [
          "--quickPlayRealms",
          "${quickPlayRealms}"
        ]
      }
    ],
```

**Comment by Jack-McKalling** [comment]
This would be my vision for how it should work;

When your instance already has worlds, its Play dropdown button should provide an option for quickplay mode, and if it hasn't already have settings for that saved, clicking the option would provide with a selection of all available worlds to choose from that instance, and once selected the setting is saved on the instance.

Since the play button already has an online and offline option, you could split the quickplay similarly as well. Both quickplay options having their own settings.

The Servers tab could have a similar quickplay button for the multiplayer mode. Since a dialogue can only display all local servers, it should also be able to provide a textfield for naming remote servers.

At all times, each instance and server should offer a dedicated settings tab for modifying or removing any previously defined quickplay settings.

**Comment by ellet0** [comment]
> When your instance already has worlds, its Play dropdown button should provide an option for quickplay mode, and if it hasn't already have settings for that saved, clicking the option would provide with a selection of all available worlds to choose from that instance, and once selected the setting is saved on the instance.
> 
> Since the play button already has an online and offline option, you could split the quickplay similarly as well. Both quickplay options having their own settings.
> 
> The Servers tab could have a similar quickplay button for the multiplayer mode.
> 
> At all times, each instance and server should offer a dedicated settings tab for modifying or removing any previously defined quickplay settings, or manually define any anew.

![image](https://github.com/ATLauncher/ATLauncher/assets/73608287/47ce3fc4-2f67-4b3f-bd7c-696334e1764d)

Did you imagine it like this? The UI still needs to be updated

**Comment by Jack-McKalling** [comment]
Yes, that would be the settings screen of an instance, offering the settings for the quick play.
Of course this is only a part of what I described. But it looks good so far.

**Comment by ellet0** [comment]
> Yes, that would be the settings screen of an instance, offering the settings for the quick play.
> Of course this is only a part of what I described. But it looks good so far.
> 

I would like to hear more about what you suggested so I can improve it
