### ISSUE TITLE
FancyMenu fails to read/write files in ATLauncher on macOS (results in crash)

### ISSUE THREAD

**Issue by Keksuccino** [ATLauncher/ATLauncher#880]
Hi, developer of [FancyMenu](https://www.curseforge.com/minecraft/mc-mods/fancymenu) here!

This is basically a copy of [an issue in FancyMenu's GitHub repo](https://github.com/Keksuccino/FancyMenu/issues/723):

- [Crash Log (gist.github.com)](https://gist.githubusercontent.com/Keksuccino/8a3b6de7780df3303cba24b09700407c/raw/55847fb07eeaa125773f7c0be9fcd2495b55d698/crash.log)
- [crashlog.txt (Download)](https://github.com/Keksuccino/FancyMenu/files/14459122/crashlog.txt)
- Unable to reproduce in macOS with:
  - CurseForge Launcher in macOS 13.X (with and without Drippy) (Mac Mini M1, 2020)
  - CurseForge Launcher in macOS 14.3.1 (with and without Drippy) (Mac Mini M1, 2020)
- Reproduced in ATLauncher on macOS with just FM installed
  - [Crash Log](https://gist.githubusercontent.com/Keksuccino/aa33e35f67991df2acdd95ef5a4d6fe6/raw/1c06088a597073d9efeeb86356fad283dffc8acc/crash.log)
  - macOS 14.3.1
  - Mac Mini M1 2020
- Also reproduced in ATLauncher on macOS with "All The Forge 10" modpack
  - macOS 14.3.1
  - Mac Mini M1 2020
- **Unable to reproduce** in ATLauncher on **Windows 10** with only FM installed
  - Game starts without any problems (no errors in log; works perfectly fine)

------------------------

## Summary

Seems like FancyMenu **fails to read and/or write files in ATLauncher on macOS**. This does not happen in the Vanilla launcher or the CurseForge launcher. It does not happen on Windows 10. This bug was reproduced in macOS 14.3.1 (Mac Mini M1 2020), but it is possible that the same bug exists in older macOS versions and/or other Macs (Intel, etc.).

**Comment by RyanTheAllmighty** [comment]
Yup, this is a known longstanding issue due to the way we package our Mac app - https://github.com/ATLauncher/ATLauncher/issues/502

Using the portable jar version of the launcher instead of the app fixes the issue.

This started happening like 3 or so OSX updates ago when Apple started to harden up FS access on apps.

This has been on my todo list to fix for a long time now, as it's coming up more and more often, but I do not have a Mac unfortunately, so it makes it more difficult to be able to just work on and fix when the mood strikes given the slowness and availability of cloud based macs.

I'll close this as a duplicate, please feel free to use #502 in your own issues to track, and feel free to repost your comment above on that issue as well for visibility

**Comment by Keksuccino** [comment]
Oh okay, I tried finding existing issues about this bug, but didn't find #502, sorry.
Great to hear there's a workaround!

Sadly I need my Mac for testing my own stuff, so I can't make it a hacky cloud solution for you via TeamViewer or something, but if you need somebody to test dev builds of the launcher, feel free to mention me in an issue (or just answer here)! I'm happy to help!
