### ISSUE TITLE
Support macOS FlatLaf theme

### ISSUE THREAD

**Issue by ellet0** [ATLauncher/ATLauncher#901]
### The Problem

It looks like ATLauncher uses [FlatLaf](https://github.com/JFormDesigner/FlatLaf) as a dependency, but it doesn't use all of its features and themes, for example, the macOS theme

![image](https://github.com/ATLauncher/ATLauncher/assets/73608287/c5e57d0a-8f3e-4180-8c2d-c1cbb9546cb8)

### The Solution

Can be applied with a single line of code:

```java

FlatMacDarkLaf.setup();

```

### Additional Information

I already checked the Theme option in the settings and it doesn't have the macOS option
![image](https://github.com/ATLauncher/ATLauncher/assets/73608287/64a33284-638a-46af-98df-3f7c52452f69)

I have noticed ATLauncher stores the theme as `String`:

```java

public String theme = Constants.DEFAULT_THEME_CLASS;

```

enum class might be a better option if the list of the items doesn't change in the runtime

and the way that is loading themes is not in a type-safe way:
![image](https://github.com/ATLauncher/ATLauncher/assets/73608287/5f40c25e-c09d-4d05-b1b3-8088c13cef60)

### Have you checked this issue doesn't already exist?

- [X] I am sure this issue doesn't exist already

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanTheAllmighty** [comment]
I'd suggest to please wait for myself to give the thumbs up on a new feature (either waiting for the issue to come out of triage, or through discussions on Discord) before raising a PR so that a discussion can be had around new features first, so that your time is not wasted in the case that we don't want certain features or if there's some other issues already, considerations that I may have already made, etc.
